### ISSUE TITLE
lnk2019 msvc

### ISSUE THREAD

**Issue by venjin** [QxOrm/QxOrm#98] opened 2023-04-23 08:48 UTC
build qxorm on qt 5.14.2 msvc2017 32 bit is success. 
than create a test project to use it. show errors lnk2019 class qx::IxDataMemberX::initData.......... and so on.
when qxorm and test both use mingw, they work well, no error.

What should i do to solve this problem?

**Comment by QxOrm** [comment] 2023-05-02 07:52
Hello, this is complicated to help you on this kind of problem because I think there is something wrong on your dev environment.
I can just confirm that I'm able to build QxOrm library and all its tests project with MSVC2019 (I use cmake to generate the solution files).

**Comment by QxOrm** [comment] 2023-05-31 10:56
Hello, I re-installed a new dev environement and I had the same issue (Qt6.5.1 and MSVC2019).
It should be fixed now if you download latest version of the source code.

**Closed by QxOrm** 2023-05-31 10:56 UTC

**Comment by venjin** [comment] 2023-09-23 07:24
> Hello, I re-installed a new dev environement and I had the same issue (Qt6.5.1 and MSVC2019).
> It should be fixed now if you download latest version of the source code.

thanks a lot

**Comment by venjin** [comment] 2023-11-11 08:22
The problem always there:
```bash
DatabaseDataAccessor.obj:-1: error: LNK2019:  "__declspec(dllimport) public: static class qx::QxClass<struct MachineInformation> * __cdecl qx::QxSingleton<class qx::QxClass<struct MachineInformation> >::getSingleton(void)" (__imp_?getSingleton@?$QxSingleton@V?$QxClass@UMachineInformation@@@qx@@@qx@@SAPAV?$QxClass@UMachineInformation@@@2@XZ)， "public: virtual class qx::IxSqlQueryBuilder & __thiscall qx::QxSqlQueryBuilder_FetchAll<struct MachineInformation>::buildSql(class QStringList const &,class qx::QxSqlRelationLinked *)" (?buildSql@?$QxSqlQueryBuilder_FetchAll@UMachineInformation@@@qx@@UAEAAVIxSqlQueryBuilder@2@ABVQStringList@@PAVQxSqlRelationLinked@2@@Z) 
MachineInformation.obj:-1: error: LNK2001:  "__declspec(dllimport) public: static class qx::QxClass<struct MachineInformation> * __cdecl qx::QxSingleton<class qx::QxClass<struct MachineInformation> >::getSingleton(void)" (__imp_?getSingleton@?$QxSingleton@V?$QxClass@UMachineInformation@@@qx@@@qx@@SAPAV?$QxClass@UMachineInformation@@@2@XZ)
```

**Comment by QxOrm** [comment] 2023-11-13 09:30
Hello,
You should not have the issue now with the latest version.
Are you able to build and execute without errors or assertions the examples projects from the ./test/ directory of QxOrm package ?
If yes, then the issue is on your project side.

**Comment by venjin** [comment] 2023-11-14 15:20
> Hello,
> You should not have the issue now with the latest version.
> Are you able to build and execute without errors or assertions the examples projects from the ./test/ directory of QxOrm package ?
> If yes, then the issue is on your project side.

Hi,
I have found that the issue is on my project.
I have not set dllexport.

**Comment by QxOrm** [comment] 2023-11-15 12:42
Great :)
